version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: idp_db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    stdin_open: true
    tty: true

  interface:
    container_name: idp_interface
    build: ./interface
    links:
      - db
    depends_on:
      - db
    ports:
      - "80:80"

  grafana:
    container_name: idp_grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    user: "0"
    volumes:
      - ./grafana:/var/lib/grafana
    links:
      - db
    depends_on:
      - db
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource

  interface_msg:
    container_name: idp_msg_interface
    build: ./interface_msg
    links:
      - db
    depends_on:
      - db
    ports:
      - "81:81"

  advertise:
    container_name: advertise
    build: ./advertise
    links:
      - db
    depends_on:
      - db
    ports:
      - "82:82"